{{- if eq .Values.global.logger_redis_location "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-redis
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-redis
  ports:
  - port: {{.Values.port}}
{{- end }}
