{{- if eq .Values.global.redisLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-redis
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-redis
{{- end }}
