{{- if eq .Values.global.redisLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-redis
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-redis
  ports:
  - port: 6379
{{- end }}
