{{- if eq .Values.global.valkeyLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-valkey
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-valkey
{{- end }}
