apiVersion: v1
kind: Secret
metadata:
  name: valkey-creds
  labels:
    app: drycc-valkey
    heritage: drycc
data: 
  {{ if eq .Values.global.valkeyLocation "on-cluster"}}
  {{- $valkeyAddrs := (list ) }}
  {{- $valkeyNodeCount := .Values.replicas | int }}
  {{- range $i := until $valkeyNodeCount }}
  {{- $valkeyAddrs = (append $valkeyAddrs (printf "drycc-valkey-%d.drycc-valkey.%s.svc.%s:6379" $i $.Release.Namespace $.Values.global.clusterDomain)) }}
  {{- end -}}
  addrs: {{ join "," $valkeyAddrs | b64enc }}
  password: {{ include "common.secrets.lookup" (dict "secret" "valkey-creds" "key" "password" "defaultValue" (randAlphaNum 32) "context" $) }}
  {{ else if eq .Values.global.valkeyLocation "off-cluster"}}
  addrs: {{ .Values.addrs | b64enc }}
  password: {{ .Values.password | b64enc }}
  {{ end }}
