name: redis
home: https://github.com/drycc/redis
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
description: A Redis database for use inside a Kubernetes cluster.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
