imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-redis"

# The following parameters are configured only when using an on-cluster Redis instance
replicas: 1

# The following parameters are configured only when using an off-cluster Redis instance
addrs: "" # A list of clusters: "127.0.0.1:7001/1,127.0.0.2:7002/1"
password: "redis password" # "" == no password

# Service
service:
  # Provide any additional service annotations
  annotations: {}

# GCP PDs and EBS volumes are supported only
persistence:
  enabled: false # Set to true to enable persistence
  size: 5Gi
  storageClass: ""

global:
  # Set the location of Workflow's redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in redis section)
  redisLocation: "on-cluster"